### ISSUE TITLE
Update turbonomic deployment to use OLM

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-tools-turbonomic#16]
- Deploy the turbonomic operator from OLM

**Comment by tcskill** [comment]
@seansund do you still want this since this isn't using gitops? Wondering if its possible to still use this - I did the code updates but the git verify workflow looks different than the latest template and it fails with a 404 error .

**Comment by smatthyssen** [comment]
@tcskill please add the blocker

**Comment by tcskill** [comment]
not needed with latest gitops module - closing
